#!/usr/bin/env python
import sys
import hyperopt.mongoexp
import logging


sys.path.append('/opt/notebooks/assignment2/')

from hyperopt import fmin, tpe, hp, STATUS_OK, STATUS_FAIL, Trials
import hyperopt.pyll.stochastic
from hyperopt.mongoexp import MongoTrials
import time
import numpy as np
from cs231n.classifiers.fc_net import *
from cs231n.data_utils import get_CIFAR10_data
from cs231n.gradient_check import eval_numerical_gradient, eval_numerical_gradient_array
from cs231n.solver import Solver

logging.basicConfig(
        stream=sys.stderr,
        level=logging.INFO)


data = get_CIFAR10_data()
for k, v in data.iteritems():
  print '%s: ' % k, v.shape


num_train = 50
small_data = {
  'X_train': data['X_train'][:num_train],
  'y_train': data['y_train'][:num_train],
  'X_val': data['X_val'],
  'y_val': data['y_val'],
}  

sys.exit(hyperopt.mongoexp.main_worker())
