#!/usr/bin/env python
import sys
import hyperopt.mongoexp
import logging
import time


logging.basicConfig(
        stream=sys.stderr,
        level=logging.INFO)
sys.exit(hyperopt.mongoexp.main_worker())
