#!/usr/bin/env python
import sys
import hyperopt.mongoexp
import logging

from hyperopt import fmin, tpe, hp, STATUS_OK, STATUS_FAIL, Trials
import hyperopt.pyll.stochastic
from hyperopt.mongoexp import MongoTrials
import time
import numpy as np
from cs231n.classifiers.fc_net import *
from cs231n.data_utils import get_CIFAR10_data
from cs231n.gradient_check import eval_numerical_gradient, eval_numerical_gradient_array
from cs231n.solver import Solver



logging.basicConfig(
        stream=sys.stderr,
        level=logging.INFO)
sys.exit(hyperopt.mongoexp.main_worker())
